In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold,train_test_split 

In [2]:
np.random.seed(42)

In [3]:
dogs_whisker_length=np.random.normal(loc=5,scale=1,size=10)
dogs_ear_flappiness_index=np.random.normal(loc=8,scale=1,size=10)

In [4]:
cats_whisker_length=np.random.normal(loc=8,scale=1,size=10)
cats_ear_flappiness_index=np.random.normal(loc=5,scale=1,size=10)

In [5]:
dogs_ear_flappiness_index

array([7.53658231, 7.53427025, 8.24196227, 6.08671976, 6.27508217,
       7.43771247, 6.98716888, 8.31424733, 7.09197592, 6.5876963 ])

In [6]:
dogs_whisker_length

array([5.49671415, 4.8617357 , 5.64768854, 6.52302986, 4.76584663,
       4.76586304, 6.57921282, 5.76743473, 4.53052561, 5.54256004])

In [7]:
cats_whisker_length

array([9.46564877, 7.7742237 , 8.0675282 , 6.57525181, 7.45561728,
       8.11092259, 6.84900642, 8.37569802, 7.39936131, 7.70830625])

In [8]:
cats_ear_flappiness_index

array([4.39829339, 6.85227818, 4.98650278, 3.94228907, 5.82254491,
       3.77915635, 5.2088636 , 3.04032988, 3.67181395, 5.19686124])

In [20]:
dogs_data=np.vstack((dogs_whisker_length,dogs_ear_flappiness_index)).T
cats_data=np.vstack((cats_whisker_length,cats_ear_flappiness_index)).T

In [21]:
dogs_data

array([[5.49671415, 7.53658231],
       [4.8617357 , 7.53427025],
       [5.64768854, 8.24196227],
       [6.52302986, 6.08671976],
       [4.76584663, 6.27508217],
       [4.76586304, 7.43771247],
       [6.57921282, 6.98716888],
       [5.76743473, 8.31424733],
       [4.53052561, 7.09197592],
       [5.54256004, 6.5876963 ]])

In [22]:
cats_data

array([[9.46564877, 4.39829339],
       [7.7742237 , 6.85227818],
       [8.0675282 , 4.98650278],
       [6.57525181, 3.94228907],
       [7.45561728, 5.82254491],
       [8.11092259, 3.77915635],
       [6.84900642, 5.2088636 ],
       [8.37569802, 3.04032988],
       [7.39936131, 3.67181395],
       [7.70830625, 5.19686124]])

In [ ]:
s